# Generated by Django 4.2 on 2024-09-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo', models.TextField()),
                ('publicado', models.BooleanField(default=False)),
                ('autor', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
